{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "test-laravel.serviceAccountName" . }}
  labels:
{{ include "test-laravel.labels" . | indent 4 }}
{{- end -}}
